device: cpu
is_debug: false
seed: 42
trainer:
  name: cvxpylayers_trainer
  max_epochs: 25
  optimizer:
    name: "Adam"
    params:
      lr: 0.001
  criterion: "custom_loss"
  batch_size: 32
  do_val: true
  val_every: 5
  early_stopping_patience: 3
  early_stopping_perc: 0.05

  loss_fn: 
     name: custom_loss_ed
     params:
      instance_path: "data/Train_Data/instance_2021_Q1_1/InputData.json"
      weights:
        supervised: 0.0
        ed_objective: 0.0001
        violations: 1.0

dataset:
  name: simple_dataset
  params:
    data_dir: "data/Train_Data"
  splits:
    train: 0.70
    val: 0.15
    test: 0.15

model:
  name: flexible_two_head_mlp
  params:
    input_size: 318
    hidden_size: 128
    num_hidden_layers: 3
    round_thermal: "threshold_ste"

ed_model:
  name: uc_model
  params:
    instance_path: "data/Train_Data/instance_2021_Q1_1/InputData.json"
    solver:

paths: 
  out_dir: "results/engaging_cvxpy_bz_32_no_sup"


